### ISSUE TITLE
PARSER-inexistant_textures

### ISSUE THREAD

**Issue by ArthurBeznik** [ArthurBeznik/42_codam_cub3D#103]
- [x] if given inexistant texture file, game still runs and crashes once reaching the texture

`./cub3D scenes/inexistant_textures.cub`

**Comment by Zangetsu89** [comment]
Done. Needed to protect if mlx_load_png fails.

**Comment by Zangetsu89** [comment]
Error fixed, but free to be fixed.

**Comment by Zangetsu89** [comment]
Fixed.

**Comment by ArthurBeznik** [comment]
Can you try this again? Not sure if its only my computer but i get:

Error
Can't read North texture path
cub3D(17814,0x1041df5c0) malloc: *** error for object 0x7a00b0000: pointer being freed was not allocated
cub3D(17814,0x1041df5c0) malloc: *** set a breakpoint in malloc_error_break to debug
./testing.sh: line 50: 17814 Abort trap: 6           ./cub3D "$file" >> out
