### ISSUE TITLE
PARSER-unopenable_textures

### ISSUE THREAD

**Issue by ArthurBeznik** [ArthurBeznik/42_codam_cub3D#107]
- [ ] if given unopenable texture file, game still runs

`./cub3D scenes/unopenable_textures.cub`

**Comment by Zangetsu89** [comment]
Error fixed, but still has leaks!

**Comment by Zangetsu89** [comment]
Fixed.

**Comment by ArthurBeznik** [comment]
And here, it should be the file that is corrupt but we get this error as well

MLX42: LodePNG: empty input buffer given to decoder. Maybe caused by non-existing file?
Error
Loading textures
cub3D(17934,0x10f23e5c0) malloc: *** error for object 0x7a00b0000: pointer being freed was not allocated
cub3D(17934,0x10f23e5c0) malloc: *** set a breakpoint in malloc_error_break to debug
./testing.sh: line 50: 17934 Abort trap: 6           ./cub3D "$file" >> out

**Comment by Zangetsu89** [comment]
fixed, free was called on an already freed allocation.
